### ISSUE TITLE
Error running ts-example

### ISSUE THREAD

**Issue by seantrace** [dgreif/ring-client-example#1]
Any idea why I am getting the following:

```
C:\Users\sean.trace\ring-client-example>npm run ts-example

> ring-client-example@1.0.0 ts-example C:\Users\sean.trace\ring-client-example
> tsc && node lib/example.js


(node:52972) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (C:\Users\sean.trace\ring-client-example\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Windows 10
Node v14.16.0

**Comment by dgreif** [comment]
Probably need to pull in the latest ring client.  I'll get it updated when I get a chance, or you can try it on your end

**Comment by dgreif** [comment]
I got everything updated and all is running well
